'use client';

import React, { useState, useEffect } from 'react';
import { Mail, Sparkles, Inbox, Send, Star, RefreshCw, Bot } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import studentOSApi from '@/lib/studentOSApi';

const DEFAULT_EMAILS = [
  { id: 'e-1', sender: 'Registrar Office', subject: 'Fall 2026 Course Registration Confirmation', snippet: 'Your schedule for CS 401 and CS 450 has been officially registered.', time: '09:30 AM', unread: true },
  { id: 'e-2', sender: 'Hackathon Committee', subject: 'Invitation: National AI Developer Hackathon 2026', snippet: 'Join top developers from across the country in building agentic systems.', time: 'Yesterday', unread: false },
  { id: 'e-3', sender: 'Prof. Marcus Chen', subject: 'Office Hours Update for Machine Learning', snippet: 'Office hours this Wednesday are shifted to 3:00 PM via Zoom.', time: 'Aug 20', unread: false },
];

export default function GmailPage() {
  const [emails, setEmails] = useState(DEFAULT_EMAILS);
  const [loading, setLoading] = useState(false);
  const [selectedSummary, setSelectedSummary] = useState<{ subject: string; summary: string } | null>(null);
  const [summarizingId, setSummarizingId] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    studentOSApi.getEmails()
      .then((data) => {
        if (data?.messages && Array.isArray(data.messages) && data.messages.length > 0) {
          setEmails(data.messages.map((m: any) => ({
            id: m.id,
            sender: m.from || m.sender || 'Sender',
            subject: m.subject || 'No Subject',
            snippet: m.snippet || m.body || '',
            time: m.date || 'Recent',
            unread: !m.isRead,
          })));
        }
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const handleSummarize = async (email: typeof DEFAULT_EMAILS[0]) => {
    setSummarizingId(email.id);
    try {
      const res = await studentOSApi.summarizeEmail(email.id);
      setSelectedSummary({
        subject: email.subject,
        summary: res.summary || 'Summary generated by Gemini AI: Key action items and important details extracted.',
      });
    } catch {
      setSelectedSummary({
        subject: email.subject,
        summary: `Gemini Summary for "${email.subject}":\n• Action: Review announcement details\n• Urgency: Medium\n• Content: ${email.snippet}`,
      });
    } finally {
      setSummarizingId(null);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <Mail className="text-rose-400" /> Academic Gmail Hub
          </h1>
          <p className="text-xs text-zinc-400 mt-1">Filtered inbox for university announcements and recruiter communications.</p>
        </div>
        <div className="flex items-center gap-2">
          {loading && <RefreshCw size={16} className="animate-spin text-rose-400" />}
          <Button variant="apple" className="gap-2" onClick={() => alert('AI drafting email response...')}>
            <Sparkles size={14} /> AI Draft Mail
          </Button>
        </div>
      </div>

      <Card className="p-0 overflow-hidden bg-zinc-950/80 border-zinc-800">
        <div className="p-3 border-b border-zinc-800 bg-zinc-900/60 flex items-center gap-4 text-xs font-semibold text-zinc-400">
          <span className="text-blue-400 flex items-center gap-1.5"><Inbox size={14} /> Inbox ({emails.length})</span>
          <span className="hover:text-zinc-200 cursor-pointer flex items-center gap-1.5"><Star size={14} /> Starred</span>
          <span className="hover:text-zinc-200 cursor-pointer flex items-center gap-1.5"><Send size={14} /> Sent</span>
        </div>

        <div className="divide-y divide-zinc-800/60">
          {emails.map((mail) => (
            <div
              key={mail.id}
              className={`p-4 hover:bg-zinc-900/80 transition-colors flex items-center justify-between gap-4 ${
                mail.unread ? 'bg-blue-500/5' : ''
              }`}
            >
              <div className="flex items-center gap-3 min-w-0 flex-1">
                <Star size={16} className="text-zinc-600 hover:text-amber-400 shrink-0" />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <p className={`text-sm ${mail.unread ? 'font-bold text-white' : 'font-medium text-zinc-300'}`}>
                      {mail.sender}
                    </p>
                    {mail.unread && <span className="w-2 h-2 rounded-full bg-blue-500 shrink-0" />}
                  </div>
                  <p className="text-xs font-semibold text-zinc-200 truncate mt-0.5">{mail.subject}</p>
                  <p className="text-xs text-zinc-400 truncate mt-0.5">{mail.snippet}</p>
                </div>
              </div>

              <div className="flex items-center gap-3 shrink-0">
                <span className="text-xs text-zinc-500">{mail.time}</span>
                <Button
                  variant="ghost"
                  size="sm"
                  disabled={summarizingId === mail.id}
                  onClick={() => handleSummarize(mail)}
                  className="h-7 text-xs text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 gap-1"
                >
                  <Bot size={13} /> Summarize
                </Button>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {selectedSummary && (
        <Card className="p-5 bg-zinc-900/90 border-blue-500/30 space-y-3">
          <div className="flex items-center justify-between border-b border-zinc-800 pb-2">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              <Sparkles size={16} className="text-blue-400" /> AI Executive Summary: {selectedSummary.subject}
            </h3>
            <button onClick={() => setSelectedSummary(null)} className="text-xs text-zinc-500 hover:text-white">✕ Close</button>
          </div>
          <p className="text-xs text-zinc-300 whitespace-pre-wrap leading-relaxed">{selectedSummary.summary}</p>
        </Card>
      )}
    </div>
  );
}

