const mongoose = require('mongoose');

/**
 * Roadmap — AI-generated, dynamically adapted career roadmap.
 * Never hardcoded. Always generated by RoadmapEngine via Gemini.
 * Auto-deleted after 90 days of inactivity (lastActivityAt TTL index).
 */
const resourceSchema = new mongoose.Schema({
  type:     { type: String, default: 'article' },
  title:    { type: String, required: true },
  url:      { type: String, default: '' },
  platform: { type: String, default: '' },
}, { _id: false });

const topicSchema = new mongoose.Schema({
  topicId:        { type: String, required: true }, // stable ID for completion tracking
  title:          { type: String, required: true },
  description:    { type: String, default: '' },
  type:           { type: String, default: 'concept' },
  resources:      [resourceSchema],
  estimatedHours: { type: Number, default: 2 },
  isCompleted:    { type: Boolean, default: false },
  completedAt:    { type: Date, default: null },
  difficulty:     { type: String, default: 'beginner' },
}, { _id: false });

const phaseSchema = new mongoose.Schema({
  phase:         { type: Number, required: true },
  title:         { type: String, required: true },
  description:   { type: String, default: '' },
  durationWeeks: { type: Number, default: 4 },
  topics:        [topicSchema],
  isUnlocked:    { type: Boolean, default: false }, // Phase 1 always unlocked
}, { _id: false });

const adaptationEntrySchema = new mongoose.Schema({
  date:           { type: Date, default: Date.now },
  trigger:        { type: String }, // "low_quiz_score", "missed_days", "mastered_topic"
  changesSummary: { type: String },
}, { _id: false });

const roadmapSchema = new mongoose.Schema(
  {
    user:    { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    profile: { type: mongoose.Schema.Types.ObjectId, ref: 'AcademicProfile', required: true },

    title:       { type: String, required: true },
    type:        { type: String, default: 'placement' },
    domain:      { type: String, required: true },
    careerGoal:  { type: String, required: true },

    status: {
      type: String,
      default: 'generating',
      index: true,
    },

    phases:      [phaseSchema],
    weakAreas:   [String],
    strongAreas: [String],

    // AI-generated gap analysis narrative
    gapAnalysis:      { type: String, default: '' },
    generatedBy:      { type: String, default: 'gemini-2.5-flash' },
    generationPrompt: { type: String, default: '' }, // stored for audit + regeneration

    // Overall completion % (computed on save via pre-hook)
    completionPercent: { type: Number, default: 0 },

    // Personalization history
    adaptationHistory: [adaptationEntrySchema],
    nextReviewDate:    { type: Date, default: null },
    lastAdaptedAt:     { type: Date, default: null },

    // 90-day inactivity TTL — MongoDB auto-deletes expired docs
    lastActivityAt:    { type: Date, default: Date.now, index: true },
  },
  { timestamps: true }
);

// Compound index: one active roadmap per user (others can be archived)
roadmapSchema.index({ user: 1, status: 1 });

// TTL index: delete if no activity for 90 days
roadmapSchema.index({ lastActivityAt: 1 }, { expireAfterSeconds: 90 * 24 * 60 * 60 });

// Auto-compute completionPercent before save
roadmapSchema.pre('save', function (next) {
  let total = 0;
  let done = 0;
  for (const phase of this.phases || []) {
    for (const topic of phase.topics || []) {
      total++;
      if (topic.isCompleted) done++;
    }
  }
  this.completionPercent = total > 0 ? Math.round((done / total) * 100) : 0;
  this.lastActivityAt = new Date();
  next();
});

module.exports = mongoose.model('Roadmap', roadmapSchema);
