module.exports = {
  // ── Existing models (unchanged) ──────────────────────────────────────────
  User: require('../modules/auth/User'),
  Subject: require('../modules/content/Subject'),
  Chapter: require('../modules/content/Chapter'),
  Progress: require('../modules/workspace/Progress'),
  Bookmark: require('../modules/workspace/Bookmark'),
  Blog: require('../modules/blog/Blog'),
  Comment: require('../modules/blog/Comment'),
  Newsletter: require('../modules/newsletter/Newsletter'),
  Todo: require('../modules/workspace/Todo'),
  Note: require('../modules/workspace/Note'),
  Contact: require('../modules/contact/Contact'),
  Series: require('../modules/series/Series'),
  IconOption: require('../modules/content/IconOption'),
  Document: require('../modules/studentos/models/Document'),
  DocumentChunk: require('../modules/studentos/models/DocumentChunk'),
  ForumCategory: require('../modules/forum/Category'),
  ForumTopic: require('../modules/forum/Topic'),
  ForumReply: require('../modules/forum/Reply'),
  Project: require('../modules/coding/models/Project'),
  CodeFile: require('../modules/coding/models/CodeFile'),
  CodeVersion: require('../modules/coding/models/CodeVersion'),
  // ── AI Roadmap Engine models (new, additive) ─────────────────────────────
  AcademicProfile: require('../modules/roadmap/models/AcademicProfile'),
  DomainConfig: require('../modules/roadmap/models/DomainConfig'),
  Roadmap: require('../modules/roadmap/models/Roadmap'),
  Assessment: require('../modules/roadmap/models/Assessment'),
  DailyPlan: require('../modules/roadmap/models/DailyPlan'),
  StudySession: require('../modules/roadmap/models/StudySession'),
  LearningResource: require('../modules/roadmap/models/LearningResource'),
};
