module.exports = {
  User: require('../modules/auth/User'),
  Subject: require('../modules/content/Subject'),
  Topic: require('../modules/content/Topic'),
  Track: require('../modules/content/Track'),
  Chapter: require('../modules/content/Chapter'),
  Progress: require('../modules/workspace/Progress'),
  Bookmark: require('../modules/workspace/Bookmark'),
  Blog: require('../modules/blog/Blog'),
  Comment: require('../modules/blog/Comment'),
  Newsletter: require('../modules/newsletter/Newsletter'),
  Todo: require('../modules/workspace/Todo'),
  Note: require('../modules/workspace/Note'),
  Contact: require('../modules/contact/Contact'),
  Series: require('../modules/series/Series'),
  IconOption: require('../modules/content/IconOption'),
  Document: require('../modules/studentos/models/Document'),
  DocumentChunk: require('../modules/studentos/models/DocumentChunk'),
};
